title: Waterfalls of Qaf
description: >- 
  A personal website
baseurl: "" # Important: No spaces after the colon except the empty quotes
url: "https://yanazuray.me"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: _sass
  style: compressed
