markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
sass:
  sass_dir: _sass
  style: compressed
